-- Laban Tran and Anthony Cavuoti
-- CS 325 - Fall 2022
-- Last modified 12/09/2022

@325design.sql;

@325populate.sql;

SET LINESIZE 200;

SET PAGESIZE 100;

COL TITLE FORMAT A30;

COL DESCRIPTION FORMAT A75;

COL REPLACE_ME_INST HEADING "INSTRUCTOR";

TTITLE "Instructors sections";

BREAK ON REPLACE_ME_INST;

SPOOL 325report2-results.txt;

PROMPT SHOWING INSTRUCTORS AND THE CLASSES THEY TEACH;

-- Equi joins various tables so that what is displayed are all
-- Instructures that work at this bootamp and the classes they
-- Teach

SELECT
    F_NAME||' '||L_NAME "REPLACE_ME_INST",
    COURSE.TITLE,
    COURSE.DESCRIPTION
FROM
    INSTRUCTOR,
    MYNAN_STAFF,
    CLASS_STAFF,
    CLASS_SECTION,
    COURSE
WHERE
    INSTRUCTOR.MYNAN_ID = MYNAN_STAFF.MYNAN_ID
    AND MYNAN_STAFF.MYNAN_ID = CLASS_STAFF.MYNAN_INSTRUCTOR_ID
    AND CLASS_STAFF.CLS_ID = CLASS_SECTION.CLS_ID
    AND CLASS_SECTION.CRS_ID = COURSE.CRS_ID
ORDER BY
    F_NAME;

SPOOL OFF;

CLEAR COLUMNS;

CLEAR BREAKS;

SET LINESIZE 80;

SET PAGESIZE 14;

TTITLE OFF;