@325design.SQL;

@325populate.SQL;

--

--

SET LINESIZE 32766;

SET PAGESIZE 32766;

PROMPT SHOWING STUDENT ABRIDGED RESUME;

BREAK ON F_NAME ON L_NAME ON EMAIL ON PHONE_NUM;

SELECT
    F_NAME,
    L_NAME,
    EMAIL,
    PHONE_NUM,
    ACCOMPLISHMENT
FROM
    STUDENT,
    RESUME,
    ACCOMPLISHMENTS,
    STUDENT_ACCOMPLISHMENTS
WHERE
    STUDENT.RESME_ID = RESUME.RSME_ID
    AND ACCOMPLISHMENTS.ACP_ID = STUDENT_ACCOMPLISHMENTS.ACP_ID
    AND STUDENT_ACCOMPLISHMENTS.STU_ID = STUDENT.STU_ID;

SET LINESIZE 80;

SET PAGESIZE 14;

CLEAR BREAKS;